# Generated by Django 2.2 on 2019-04-20 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diskarray', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='storage_class',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='filecopy',
            name='disk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copies', to='diskarray.Disk'),
        ),
    ]
